src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $last_name;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Unique
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Controller/ClientsController.php
<?php
// src/Controller/ClientsController.php
namespace App\Controller;

use Doctrine\DBAL\DBALException;
use Doctrine\DBAL\Driver\PDOException;
use Doctrine\ORM\ORMException;
use Swift_Mailer;
use Swift_Message;
use Swift_SmtpTransport;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Client;

class ClientsController extends AbstractController
{

    private $titles = ['mr', 'ms', 'mrs', 'dr', 'mx'];

    /**
     * @Route("/clients", name="clients")
     */

    public function showIndex()
    {
        $clients = $this->getDoctrine()->getRepository(Client::class)->findAll();
        $data = array(
            "clients" => $clients
        );

//        $routeName= $_SERVER["BASE"];
//        return $this->render("clients/index.html.twig",
//            [
//                "base_url" => $routeName
//            ]);

        return $this->render("clients/index.html.twig",$data);

    }

    /**
     * @Route("/clients/modify/{id_client}", name="modify")
     */
    public function showDetails(Request $request, $id_client)
    {

        $clients = $this->getDoctrine()->getRepository(Client::class)
            ->find($id_client);

        $data = array(
            "clients" => $clients,
            "mode"    => "modify",
            "form"    => []
        );

        $data["titles"] = $this->titles;

        $form = $this->createFormBuilder()
            ->add("name")
            ->add("last_name")
            ->add("title")
            ->add("address")
            ->add("zip_code")
            ->add("city")
            ->add("state")
            ->add("email")
            ->getForm();

        // verify if a data sending or not
        $form->handleRequest($request);

        if($form->isSubmitted())
        {
            $get_data = $form->getData();
            $data["form"] = [];
            $data["form"] = $get_data;

            $clients->setTitle($get_data["title"]);
            $clients->setName($get_data["name"]);
            $clients->setLastName($get_data["last_name"]);
            $clients->setAddress($get_data["address"]);
            $clients->setZipCode($get_data["zip_code"]);
            $clients->setCity($get_data["city"]);
            $clients->setState($get_data["state"]);
            $clients->setEmail($get_data["email"]);

            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirectToRoute("clients");
        }
        else
        {
            $data["form"] = $clients;
        }

        return $this->render("clients/form.html.twig",$data);

    }

    /**
     * @Route("/clients/new", name="new")
     */
    public function showNew(Request $request, \Swift_Mailer $mailer)
    {
        $data = array(
            "mode"    => "new",
            "form"    => [],
            "titles"  => $this->titles
        );

        $data["form"]["title"] = "";


        $form = $this->createFormBuilder()
            ->add("title")
            ->add("name")
            ->add("last_name")
            ->add("address")
            ->add("zip_code")
            ->add("city")
            ->add("state")
            ->add("email")
            ->getForm();

        // verify if a data sending or not
        $form->handleRequest($request);

        if($form->isSubmitted())
        {
            $get_data = $form->getData();
            $data["form"] = [];
            $data["form"] = $get_data;

            $em = $this->getDoctrine()->getManager();
            $client = new Client();
            $client->setTitle($get_data["title"]);
            $client->setName($get_data["name"]);
            $client->setLastName($get_data["last_name"]);
            $client->setAddress($get_data["address"]);
            $client->setZipCode($get_data["zip_code"]);
            $client->setCity($get_data["city"]);
            $client->setState($get_data["state"]);
            $client->setEmail($get_data["email"]);

            try {
                $em->persist($client);
                $em->flush();
                $message = 'Done';
            } catch (DBALException $e) {
                $message = sprintf('DBALException [%i]: %s', $e->getCode(), $e->getMessage());
            } catch (PDOException $e) {
                $message = sprintf('PDOException [%i]: %s', $e->getCode(), $e->getMessage());
            } catch (ORMException $e) {
                $message = sprintf('ORMException [%i]: %s', $e->getCode(), $e->getMessage());
            } catch (Exception $e) {
                $message = sprintf('Exception [%i]: %s', $e->getCode(), $e->getMessage());
            }

            echo $message;
            $transport = (new Swift_SmtpTransport('smtp.mailtrap.io', 2525))
                ->setUsername('135849b1c3b348') // generated by Mailtrap
                ->setPassword('966809f26596d2') // generated by Mailtrap
            ;
            $mailer = new Swift_Mailer($transport);
            // Add subject
            $message = (new \Swift_Message('Hello Email'))
                //Put the From address
            ->setFrom(['davidelpaula@gmail.com'])
            // Include several To addresses
            ->setTo([$client->getEmail() => 'New Mailtrap user']);

            $message->setBody('<p>Welcome to Maitrap!</p>
            Now your test emails will be <i>safe</i>', 'text/html');
            $message->addPart('Welcome to Mailtrap, now your test emails will be safe', 'text/plain');
            $mailer->send($message);

            return $this->redirectToRoute("clients");
        }

        return $this->render("clients/form.html.twig",$data);
    }

}

templates/clients/form.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
      <div class="medium-12 large-12 columns">
        <h4>{{ mode | capitalize}} Client</h4>
        <form action="" method="post">
          <div class="medium-4  columns">
            <label>Title</label>
            <select name="form[title]">
              {% for title in titles %}
              <option value="{{ title }}" {{ title == form.title ? "selected" : "" }}>{{ title | capitalize }}.</option>
              {% endfor %}
            </select>
          </div>
          <div class="medium-4  columns">
            <label>Name</label>
            <input name="form[name]" value="{{ form.name is defined ? form.name : "" }}" type="text" />
          </div>
          <div class="medium-4  columns">
            <label>Last Name</label>
            <input name="form[last_name]" value="{{ form.lastName is defined ? form.lastName : "" }}" type="text" />
          </div>
          <div class="medium-8  columns">
            <label>Address</label>
            <input name="form[address]" value="{{ form.address is defined ? form.address : "" }}" type="text" />
          </div>
          <div class="medium-4  columns">
            <label>Zip Code</label>
            <input name="form[zip_code]" value="{{ form.zipCode is defined ? form.zipCode : "" }}" type="text" />
          </div>
          <div class="medium-4  columns">
            <label>City</label>
            <input name="form[city]" value="{{ form.city is defined ? form.city : "" }}" type="text" />
          </div>
          <div class="medium-4  columns">
            <label>State</label>
            <input name="form[state]" value="{{ form.state is defined ? form.state : "" }}" type="text" />
          </div>
          <div class="medium-12  columns">
            <label>Email</label>
            <input name="form[email]" value="{{ form.email is defined ? form.email : "" }}" type="text" />
          </div>
          <div class="medium-12  columns">
            <input type="submit" value="SAVE" class="button success hollow" />
          </div>
        </form>
      </div>
    </div>

{% endblock %}

templates/clients/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
      <div class="medium-12 large-12 columns">
        <h4>Clients</h4>
        <div class="medium-2  columns"><a class="button" href="{{ path("new") }}">ADD NEW CLIENT</a></div>

        <table class="stack">
          <thead>
            <tr>
              <th width="200">Name</th>
              <th width="200">Email</th>
              <th width="200">Address</th>
              <th width="200">Action</th>
            </tr>
          </thead>
          {%  for client in clients %}
              <tr>
                <td>{{ client.title | capitalize }}. {{ client.name }} {{ client.lastName }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.state }}, {{ client.city }}, {{ client.address }}, {{ client.zipCode }}</td>
                <td>
                  <a class="hollow button" href="{{ path("modify",{ "id_client": client.id }) }}">EDIT</a>
                  <a class="hollow button warning" href="{{ path("booking", {"id_client": client.id }) }}">BOOK A ROOM</a>
                </td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

{% endblock %}